### ISSUE TITLE
상태 동기화 실패

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Cron-Event#3]
#2 를 배포하고 오타로 인해서 2019-01-17 일 실행되는 2019-01-16 일 대여자의 상태 변경이 실패했습니다.

**Comment by aanoaa** [comment]
이 문제를 해결해서 https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-Cron-Event-v0.1.5.tar.gz 새로운 버전을 배포/업그레이드/재시작 하였습니다.
7a99debd941a985cc5e11ba955cb4ebde8524fca

**Comment by aanoaa** [comment]
지난밤의 로그를 살펴봤는데 이상없는 것 같습니다.

**Comment by pingpongworks** [comment]
네, 아침에 확인했을 때 어제 대여내역이 정상적으로 `대여완료`상태인 것을 확인했습니다. 오늘 하루 더 확인해보겠습니다. 그저께 내역은 아직 예약중으로 남아있는데, 수동으로 상태를 바꾸겠습니다.
